In [48]:
import os
import pandas as pd
import calendar
import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.animation
import pandas as pd

In [2]:
path = os.getcwd() # getting the path of current working directory to create the folder structure
configfile = os.path.join(path + '\Final Project Data\IMDB_Movies_Csv\Movies_Gross.csv') # getting the path of the json files to be read

In [41]:
#fields = ['DATE', 'BOROUGH']
all_movies = pd.DataFrame.from_csv(configfile, encoding = "ISO-8859-1").reset_index()
all_movies
all_movies = all_movies.replace('None','0')
all_movies

,IMDB_ID,Title,Rating,Budget,Gross,Year,Country
0,tt0012190,The Four Horsemen of the Apocalypse,7.9,800000,0,0,0
1,tt0013099,The Electric House,7.3,0,33,2002,Spain
2,tt0013099,The Electric House,7.3,0,0,0,0
3,tt0017765,College,7.1,0,23993,2002,Spain
4,tt0017765,College,7.1,0,0,0,0
5,tt0018037,The Jazz Singer,6.8,422000,0,0,0
6,tt0018455,Sunrise,8.3,0,14406,2004,UK
7,tt0018455,Sunrise,8.3,0,13918,2004,UK
8,tt0018455,Sunrise,8.3,0,13861,2004,UK
9,tt0018455,Sunrise,8.3,0,13644,2004,UK
10,tt0018455,Sunrise,8.3,0,13534,2004,UK
11,tt0018455,Sunrise,8.3,0,13130,2004,UK
12,tt0018455,Sunrise,8.3,0,12885,2004,UK
13,tt0018455,Sunrise,8.3,0,12677,2004,UK
14,tt0018455,Sunrise,8.3,0,12392,2004,UK
15,tt0018455,Sunrise,8.3,0,10839,2004,UK
16,tt0018455,Sunrise,8.3,0,10125,2004,UK
17,tt0018455,Sunrise,8.3,0,9240,2004,UK
18,tt0018455,Sunrise,8.3,0,5801,2004,UK
19,tt0018455,Sunrise,8.3,0,97576,2004,Italy
20,tt0018455,Sunrise,8.3,0,32695,2004,Italy
21,tt0018455,Sunrise,8.3,0,8883,2004,Italy
22,tt0018455,Sunrise,8.3,0,44322,2005,Portugal
23,tt0018455,Sunrise,8.3,0,5130,2002,Spain
24,tt0019729,The Broadway Melody,6.3,379000,0,0,except
25,tt0020466,Sunnyside Up,6.8,0,0,0,0
26,tt0020629,All Quiet on the Western Front,8.1,1448864,0,0,0
27,tt0023876,Cavalcade,6.0,1180280,0,0,0
28,tt0025617,The Painted Veil,6.6,947000,0,0,except
29,tt0025617,The Painted Veil,6.6,947000,0,0,0
...,...,...,...,...,...,...,...
17619,tt4035268,Cosmos,5.9,0,3807,2016,USA
17620,tt4048050,Trois souvenirs de ma jeunesse,6.9,0,268548,2016,USA
17621,tt4048050,Trois souvenirs de ma jeunesse,6.9,0,266852,2016,USA
17622,tt4048050,Trois souvenirs de ma jeunesse,6.9,0,262538,2016,USA
17623,tt4048050,Trois souvenirs de ma jeunesse,6.9,0,252095,2016,USA
17624,tt4048050,Trois souvenirs de ma jeunesse,6.9,0,218255,2016,USA
17625,tt4048050,Trois souvenirs de ma jeunesse,6.9,0,174684,2016,USA
17626,tt4048050,Trois souvenirs de ma jeunesse,6.9,0,120029,2016,USA
17627,tt4048050,Trois souvenirs de ma jeunesse,6.9,0,65743,2016,USA
17628,tt4048050,Trois souvenirs de ma jeunesse,6.9,0,26847,2016,USA
17629,tt4136084,Florence Foster Jenkins,6.9,29000000,27370107,2016,USA
17630,tt4136084,Florence Foster Jenkins,6.9,29000000,27321247,2016,USA
17631,tt4136084,Florence Foster Jenkins,6.9,29000000,27249911,2016,USA
17632,tt4136084,Florence Foster Jenkins,6.9,29000000,27154455,2016,USA
17633,tt4136084,Florence Foster Jenkins,6.9,29000000,26954148,2016,USA
17634,tt4136084,Florence Foster Jenkins,6.9,29000000,25723456,2016,USA
17635,tt4136084,Florence Foster Jenkins,6.9,29000000,19820821,2016,USA
17636,tt4136084,Florence Foster Jenkins,6.9,29000000,2080000,2016,USA
17637,tt4136084,Florence Foster Jenkins,6.9,29000000,2080000,2016,Worldwide
17638,tt4136084,Florence Foster Jenkins,6.9,29000000,2731899,2017,Italy
17639,tt4136084,Florence Foster Jenkins,6.9,29000000,2640896,2017,Italy
17640,tt4136084,Florence Foster Jenkins,6.9,29000000,2434580,2017,Italy
17641,tt4136084,Florence Foster Jenkins,6.9,29000000,1839969,2017,Italy
17642,tt4242844,Wei ai zhi jian ru jia jing,4.3,0,271451,2015,USA
17643,tt4258292,Yennai Arindhaal,7.3,0,1065000000,2015,worldwide
17644,tt4272866,Le Garçon et la Bête,7.7,0,446142,2016,USA
17645,tt4272866,Le Garçon et la Bête,7.7,0,274247,2016,USA
17646,tt4272866,Le Garçon et la Bête,7.7,0,32329,2016,Spain
17647,tt4315956,Oneului yeonae,6.3,4000000,32211,2015,USA
17648,tt4315956,Oneului yeonae,6.3,4000000,11600,2015,USA

In [42]:
all_movies['Gross']= pd.to_numeric(all_movies['Gross'])

In [43]:
Gross_Grouped = pd.DataFrame(all_movies.groupby(['IMDB_ID','Title','Country','Rating'], sort = True)['Gross'].sum().reset_index()) # grouping by month for manhattand data and

In [45]:
Gross_Grouped = Gross_Grouped[Gross_Grouped['Country']!='0']
Gross_Grouped = Gross_Grouped[Gross_Grouped['Country']!='except']

In [47]:
x = Gross_Grouped[Gross_Grouped['Title']=='Avatar']
x

        IMDB_ID   Title      Country  Rating        Gross
2089  tt0499549  Avatar    Argentina     7.8    233241346
2090  tt0499549  Avatar        China     7.8    204000000
2091  tt0499549  Avatar        Italy     7.8    359379877
2092  tt0499549  Avatar  Philippines     7.8   2198185174
2093  tt0499549  Avatar     Portugal     7.8      9294777
2094  tt0499549  Avatar       Russia     7.8   2405768578
2095  tt0499549  Avatar        Spain     7.8    227472062
2096  tt0499549  Avatar           UK     7.8   1152472481
2097  tt0499549  Avatar          USA     7.8  31902136559
2098  tt0499549  Avatar    Worldwide     7.8   5570240259

In [49]:
Gross_Grouped.head()

     IMDB_ID               Title   Country  Rating   Gross
2  tt0013099  The Electric House     Spain     7.3      33
4  tt0017765             College     Spain     7.1   23993
6  tt0018455             Sunrise     Italy     8.3  139154
7  tt0018455             Sunrise  Portugal     8.3   44322
8  tt0018455             Sunrise     Spain     8.3    5130

In [74]:
x = Gross_Grouped['Country']
y = Gross_Grouped['Rating']
z = Gross_Grouped['Gross']
#d = np.array(Gross_Grouped[Gross_Grouped['Rating']>=0]).flatten()
df = pd.DataFrame({"x" : x, "y" : y, "z" : z})

In [82]:
def update_graph():
    data=df
    graph.set_data (data.x, data.y)
    graph.set_3d_properties(data.z)
    title.set_text('3D Test')
    return graph

In [77]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
title = ax.set_title('3D Test')

data=df
graph, = ax.plot(data.x, data.y, data.z, linestyle="", marker="o")

ani = matplotlib.animation.FuncAnimation(fig, update_graph, 19, 
                               interval=40, blit=True)

plt.show()

KeyError: 0

In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d.axes3d as axes3d

columns = ['Country', 'Rating', 'Gross']
df = pd.DataFrame(Gross_Grouped, columns = columns)
 
#N = 12
#arr = np.arange(N*2).reshape(N,2)
#words = np.array(['foo', 'bar', 'baz', 'quux', 'corge'])
#x = pd.DataFrame(df,columns=list('XYZ'))
#IMDB_ID	Title	Country	Rating	Gross
#df['Z'] = np.linspace(1, 1000, N)
Z = df['Gross']
Xuniques, X = np.unique(df['Country'], return_inverse=True)
Y = df['Rating']
# Yuniques, Y = np.unique(df['Y'], return_inverse=True)
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1, projection='3d')
ax.scatter(X, Y, Z, s=20, c='b')
ax.set(xticks=range(len(Xuniques)), xticklabels=Xuniques)

ani = matplotlib.animation.FuncAnimation(fig, update_graph, 19,interval=40, blit=True)
plt.show()

TypeError: update_graph() takes 0 positional arguments but 1 was given

In [ ]:
all_movies.groupby('Country', sort = True)